# Generated by Django 6.0.1 on 2026-01-06 20:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoteCultivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_lote", models.CharField(max_length=50, unique=True)),
                ("finca", models.CharField(max_length=200)),
                ("variedad", models.CharField(max_length=100)),
                ("hectareas", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fecha_siembra", models.DateField()),
                ("fecha_cosecha", models.DateField()),
                ("responsable", models.CharField(max_length=200)),
                ("certificacion_organica", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Lote de Cultivo",
                "verbose_name_plural": "Lotes de Cultivo",
            },
        ),
        migrations.CreateModel(
            name="ProcesoTransformacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_lavado", models.DateTimeField()),
                ("responsable_lavado", models.CharField(max_length=200)),
                ("metodo_lavado", models.CharField(max_length=100)),
                ("fecha_empaquetado", models.DateTimeField()),
                ("tipo_empaque", models.CharField(max_length=100)),
                (
                    "cantidad_empaquetada",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("unidad_medida", models.CharField(max_length=50)),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="procesos",
                        to="core.lotecultivo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proceso de Transformación",
                "verbose_name_plural": "Procesos de Transformación",
            },
        ),
        migrations.CreateModel(
            name="ControlCalidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_control", models.DateTimeField(auto_now_add=True)),
                ("inspector", models.CharField(max_length=200)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("A", "Aprobado"),
                            ("R", "Rechazado"),
                            ("P", "Pendiente"),
                        ],
                        default="P",
                        max_length=1,
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
                (
                    "brix",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("defectos", models.TextField(blank=True)),
                ("observaciones", models.TextField(blank=True)),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="controles",
                        to="core.procesotransformacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Control de Calidad",
                "verbose_name_plural": "Controles de Calidad",
            },
        ),
        migrations.CreateModel(
            name="Transporte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_salida", models.DateTimeField()),
                ("fecha_entrega", models.DateTimeField(blank=True, null=True)),
                ("vehiculo", models.CharField(max_length=100)),
                ("conductor", models.CharField(max_length=200)),
                ("destino", models.CharField(max_length=200)),
                (
                    "temperatura_minima",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[django.core.validators.MinValueValidator(-20)],
                    ),
                ),
                (
                    "temperatura_maxima",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=4,
                        validators=[django.core.validators.MaxValueValidator(30)],
                    ),
                ),
                (
                    "temperatura_promedio",
                    models.DecimalField(decimal_places=1, max_digits=4),
                ),
                ("recibido_por", models.CharField(blank=True, max_length=200)),
                ("estado_entrega", models.CharField(blank=True, max_length=50)),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transportes",
                        to="core.lotecultivo",
                    ),
                ),
                (
                    "proceso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transportes",
                        to="core.procesotransformacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transporte",
                "verbose_name_plural": "Transportes",
            },
        ),
    ]
